### ISSUE TITLE
Publish to npm?

### ISSUE THREAD

**Issue by matthiasgeihs** [Nikkei/nid-webauthn-emulator#75]
Hey, nice project!

Did you think about publishing this to `npmjs.com` so that it becomes available via `npm i nid-webauthn-emulator`?

**Comment by phwinx** [comment]
@matthiasgeihs Thank you for your request.
Now I published this product to `npmjs.com` and you can get it via `npm i nid-webauthn-emulator`

**Comment by matthiasgeihs** [comment]
very cool, thank you

**Comment by matthiasgeihs** [comment]
@phwinx I noticed that you changed the package name from `@nikkei/nid-webauthn-emaultor` to `nid-webauthn-emaultor`.

Acutally, I think including the company name (as in `@nikkei/nid-webauthn-emaultor`) would be more conventional. Sorry for my incomplete suggestion. Anyhow, both is fine, just wanted to let you know that it was not my intention to require changing the package name.

**Comment by phwinx** [comment]
@matthiasgeihs I understood that this issue wasn't requesting a package name change and was only asking for publishing to npmjs. There was some discussion about including the organization name in the package name, but due to several reasons within the organization, we decided not to include it and named it nid-webauthn-emulator. Thank you.
